name: OffsetInc
favicon: null
layout_spectrum: 0.37803
typography_spectrum: 0.46819
title: 'About Offset Industries '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f833c'
    - '#80914a'
    - '#909b59'
    - '#54652f'
    - '#9ea766'
  brandStrength: 0.3125
  lightness: 0.21167650818824768
  saturation: 0.6146067939698696
  rhythmicContrast: 0.5
purpose: []
